[0m11:09:02.720219 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a957cb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bf9b4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bf9b750>]}


============================== 11:09:02.729889 | 508952aa-6ac2-40e5-b0bd-0c92ba9049a7 ==============================
[0m11:09:02.729889 [info ] [MainThread]: Running with dbt=1.10.11
[0m11:09:02.730768 [debug] [MainThread]: running dbt with arguments {'version_check': 'True', 'empty': 'False', 'invocation_command': 'dbt run --profiles-dir /Users/anton/Desktop/air-quality-dataops/data_transformation/air_quality_dbt', 'warn_error': 'None', 'indirect_selection': 'eager', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'cache_selected_only': 'False', 'partial_parse': 'True', 'printer_width': '80', 'log_path': 'logs', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'use_experimental_parser': 'False', 'use_colors': 'True', 'quiet': 'False', 'send_anonymous_usage_stats': 'True', 'debug': 'False', 'log_cache_events': 'False', 'profiles_dir': '/Users/anton/Desktop/air-quality-dataops/data_transformation/air_quality_dbt', 'write_json': 'True', 'fail_fast': 'False', 'target_path': 'None'}
[0m11:09:02.731611 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/anton/Desktop/air-quality-dataops/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:09:02.733098 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.111527845, "process_in_blocks": "0", "process_kernel_time": 0.185034, "process_mem_max_rss": "96743424", "process_out_blocks": "0", "process_user_time": 1.814146}
[0m11:09:02.733959 [debug] [MainThread]: Command `dbt run` failed at 11:09:02.733789 after 0.11 seconds
[0m11:09:02.734504 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c028050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bfce570>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10be31d00>]}
[0m11:09:02.734967 [debug] [MainThread]: Flushing usage events
[0m11:09:03.859999 [debug] [MainThread]: An error was encountered while trying to flush usage events
